import { ABfyProvider } from "@repo/abfy/AbfyContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <ABfyProvider backendUrl="https://webhook.site/89a562a1-b9ad-4b35-a909-c0811c3bf077">
        <body className={inter.className}>{children}</body>
      </ABfyProvider>
    </html>
  );
}
