import { AbfyProvider } from "@repo/abfy/AbfyContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <AbfyProvider backendUrl="https://webhook.site/35a56e33-dff6-468d-9fb4-a3e3b5ae0ddc">
        <body className={inter.className}>{children}</body>
      </AbfyProvider>
    </html>
  );
}
